output "generated_label" {
  description = "Label generated by the nested child module."
  value       = module.nested_label.generated_label
}

output "created_at" {
  description = "Creation timestamp from the nested child module."
  value       = module.nested_label.created_at
}

output "expires_at" {
  description = "Expiration timestamp from the nested child module."
  value       = module.nested_label.expires_at
}
