output "generated_label" {
  description = "Label generated by the component source module."
  value       = module.utility_component.generated_label
}

output "created_at" {
  description = "Creation timestamp from the component source module."
  value       = module.utility_component.created_at
}

output "expires_at" {
  description = "Expiration timestamp from the component source module."
  value       = module.utility_component.expires_at
}
