output "generated_label" {
  description = "Label generated by the governable defaults component flow."
  value       = module.utility_component.generated_label
}

output "created_at" {
  description = "Creation timestamp from the governable defaults component flow."
  value       = module.utility_component.created_at
}

output "expires_at" {
  description = "Expiration timestamp from the governable defaults component flow."
  value       = module.utility_component.expires_at
}

output "effective_ttl_hours" {
  description = "Final ttl_hours value used after variable/local resolution."
  value       = local.effective.ttl_hours
}
