variable "name_prefix" {
  description = "Prefix used for the generated random label."
  type        = string
}

variable "pet_length" {
  description = "Number of words generated by random_pet."
  type        = number
}

variable "separator" {
  description = "Separator placed between random_pet words."
  type        = string
}

variable "ttl_hours" {
  description = "Number of hours to add to the creation timestamp."
  type        = number
}
